### ISSUE TITLE
adjusting config in aws-lc, libressl branches

### ISSUE THREAD

**Issue by chipitsine** [haproxytech/haproxy-qns#3]
can we please apply this patch https://github.com/haproxytech/haproxy-qns/commit/81f3b943767a54a897dd3f5de15733bbef131d4d to aws-lc and libressl branches ?

**Comment by a-denoyelle** [comment]
Done, thanks for the remainder.
However I thought aws-lc and libressl branches were integrated on the master Dockerfile. I see that you have some unmerged work for this for aws-lc, is it mergeable in master ?

**Comment by chipitsine** [comment]
it was only AWS-LC for the moment. I didn't find acceptable way to hack quic.cfg (which is different for LibreSSL).

I'll have a look.

**Comment by chipitsine** [comment]
It is mergeable now.
